### ISSUE TITLE
two instances of airtable.json

### ISSUE THREAD

**Issue by okdistribute** [digidem/lagarto-cocha-map#7]
There is one in the root and one under `static`. The root one is updated at latest but the `static` one is served. We should probably update the one in `static` rather than the one in `root` to reduce confusion

**Comment by gmaclennan** [comment]
This is fixed in 00b983822b41028ca783d961179f647c84b19683. The `airtable.json` that is updated is the one in root. This is updated in both the master and gh-pages branches when Airtable is updated. This ensures that updates appear for anything served from gh-pages without needing to push another depolyment to gh-pages. I added a symbolic link from static/airtable.json to the one in root, so that serving a local testing version still works.
